//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.225.
// 
#pragma warning disable 1591

namespace CheckAsm.net.booring.checkasm1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="StatsBinding", Namespace="http://checkasm.booring.net/")]
    public partial class Stats : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RecordInstallationOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecordStartOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Stats() {
            this.Url = global::CheckAsm.Properties.Settings.Default.CheckAsm_net_booring_checkasm1_Stats;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RecordInstallationCompletedEventHandler RecordInstallationCompleted;
        
        /// <remarks/>
        public event RecordStartCompletedEventHandler RecordStartCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://checkasm.booring.net/errorreporting#RecordInstallation", RequestNamespace="http://checkasm.booring.net/errorreporting", ResponseNamespace="http://checkasm.booring.net/errorreporting")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string RecordInstallation(string customerId) {
            object[] results = this.Invoke("RecordInstallation", new object[] {
                        customerId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecordInstallationAsync(string customerId) {
            this.RecordInstallationAsync(customerId, null);
        }
        
        /// <remarks/>
        public void RecordInstallationAsync(string customerId, object userState) {
            if ((this.RecordInstallationOperationCompleted == null)) {
                this.RecordInstallationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecordInstallationOperationCompleted);
            }
            this.InvokeAsync("RecordInstallation", new object[] {
                        customerId}, this.RecordInstallationOperationCompleted, userState);
        }
        
        private void OnRecordInstallationOperationCompleted(object arg) {
            if ((this.RecordInstallationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecordInstallationCompleted(this, new RecordInstallationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://checkasm.booring.net/errorreporting#RecordStart", RequestNamespace="http://checkasm.booring.net/errorreporting", ResponseNamespace="http://checkasm.booring.net/errorreporting")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string RecordStart(string customerId) {
            object[] results = this.Invoke("RecordStart", new object[] {
                        customerId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecordStartAsync(string customerId) {
            this.RecordStartAsync(customerId, null);
        }
        
        /// <remarks/>
        public void RecordStartAsync(string customerId, object userState) {
            if ((this.RecordStartOperationCompleted == null)) {
                this.RecordStartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecordStartOperationCompleted);
            }
            this.InvokeAsync("RecordStart", new object[] {
                        customerId}, this.RecordStartOperationCompleted, userState);
        }
        
        private void OnRecordStartOperationCompleted(object arg) {
            if ((this.RecordStartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecordStartCompleted(this, new RecordStartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RecordInstallationCompletedEventHandler(object sender, RecordInstallationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecordInstallationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecordInstallationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RecordStartCompletedEventHandler(object sender, RecordStartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecordStartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecordStartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591